name: readback
description: ReadBack ” --org com.example.readback”
version: 1.0.5+16
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: 3.7.11

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.7.2
  flutter_easyloading: ^3.0.5
  get_it: ^8.2.0
  injectable: ^2.5.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  dropdown_button2: ^2.3.9
  link_text: ^0.2.1
  package_info_plus: ^8.3.1
  pretty_dio_logger: ^1.4.0
  google_nav_bar: ^5.0.7
  connectivity_plus: ^6.1.5
  http: ^1.5.0
  sign_in_with_apple: ^7.0.1
  auto_size_text: ^3.0.0
  lottie: ^3.3.1
  calendar_date_picker2: ^2.0.1
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.4.0
  font_awesome_flutter: ^10.9.1
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_18pt_regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  mage_path: "assets/images/github_logo.png"
